name: Run tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -r actions/requirements-actions.txt
      - name: Lint
        run: |
          black --check actions
          isort -rc -c actions
          flake8 actions
          mypy actions
      - name: Test model
        run: |
          rasa data validate
          rasa train
          rasa test --fail-on-prediction-errors
